import './globals.css';
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import { Inter } from 'next/font/google';
import { StateContext } from './context/StateContext';
import { Navbar } from '@/components';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StateContext>
          <main>
            <Navbar />
            {children}
          </main>
        </StateContext>
      </body>
    </html>
  );
}
